services:
  app:
    image: ${DOCKER_IMAGE}
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: portfolio_app
    ports:
      - "${PORT}:3000"
    environment:
      # Admin credentials
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      # Database connection
      DB_HOST: database
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}

      # n8n webhook
      N8N_WEBHOOK_URL: ${N8N_WEBHOOK_URL}

      # Node environment
      NODE_ENV: production
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - social_media_manager_network

  database:
    image: mysql:8.0
    restart: unless-stopped
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - social_media_manager_network

networks:
  social_media_manager_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
